/**
 * Typical service catalogue with regional average prices, injected into a generated concept so
 * the "Цены" / "Меню" / "Каталог" section is never a thin, generic placeholder. Prices are rough
 * SNG averages in tenge (₸) and are explicitly framed as editable — the concept is a starting
 * point, not a real menu. Depth is deliberately realistic per niche (a coffee shop's menu really
 * does run 25-30 items, a barbershop's price list really does run 15-20) — a 3-4 item stub reads
 * as an unfinished demo, not "a coffee shop."
 */

export type ConceptService = { name: string; price: string };
export type ConceptServiceCatalog = { items: ConceptService[]; note: string };

const NOTE = "Средние цены по региону — их можно изменить.";

const CATALOGS = {
  barbershop: [
    { name: "Мужская стрижка", price: "3 500 ₸" },
    { name: "Стрижка машинкой", price: "2 500 ₸" },
    { name: "Стрижка + борода", price: "5 500 ₸" },
    { name: "Моделирование бороды", price: "2 500 ₸" },
    { name: "Бритьё опасной бритвой", price: "3 000 ₸" },
    { name: "Камуфляж седины", price: "4 000 ₸" },
    { name: "Тонирование бороды", price: "3 500 ₸" },
    { name: "Детская стрижка", price: "3 000 ₸" },
    { name: "Отец + сын", price: "6 000 ₸" },
    { name: "Стрижка + мытьё головы", price: "4 000 ₸" },
    { name: "Камуфляж бороды", price: "3 200 ₸" },
    { name: "Оформление усов", price: "1 500 ₸" },
    { name: "Уход за кожей лица", price: "4 500 ₸" },
    { name: "Чистка лица", price: "5 500 ₸" },
    { name: "Стрижка носа и ушей", price: "1 200 ₸" },
    { name: "Комплекс «Стрижка + борода + уход»", price: "8 500 ₸" },
    { name: "Экспресс-стрижка (30 мин)", price: "2 800 ₸" },
    { name: "VIP-обслуживание", price: "12 000 ₸" },
  ],
  beauty: [
    { name: "Маникюр с покрытием", price: "6 000 ₸" },
    { name: "Маникюр без покрытия", price: "3 500 ₸" },
    { name: "Педикюр", price: "7 000 ₸" },
    { name: "Комплекс маникюр + педикюр", price: "12 000 ₸" },
    { name: "Наращивание ногтей", price: "10 000 ₸" },
    { name: "Снятие покрытия", price: "1 500 ₸" },
    { name: "Стрижка и укладка", price: "5 000 ₸" },
    { name: "Окрашивание в один тон", price: "12 000 ₸" },
    { name: "Мелирование / балаяж", price: "20 000 ₸" },
    { name: "Тонирование волос", price: "8 000 ₸" },
    { name: "Кератиновое выпрямление", price: "25 000 ₸" },
    { name: "Брови: коррекция + окрашивание", price: "4 000 ₸" },
    { name: "Ламинирование бровей", price: "5 000 ₸" },
    { name: "Ламинирование ресниц", price: "7 000 ₸" },
    { name: "Наращивание ресниц", price: "9 000 ₸" },
    { name: "Дневной макияж", price: "8 000 ₸" },
    { name: "Вечерний макияж", price: "12 000 ₸" },
    { name: "Чистка лица", price: "10 000 ₸" },
    { name: "Массаж лица", price: "6 000 ₸" },
    { name: "Депиляция воском (зона)", price: "от 2 000 ₸" },
    { name: "SPA-уход для рук", price: "5 000 ₸" },
    { name: "Свадебный образ", price: "35 000 ₸" },
  ],
  coffee: [
    { name: "Эспрессо", price: "700 ₸" },
    { name: "Американо", price: "900 ₸" },
    { name: "Капучино", price: "1 200 ₸" },
    { name: "Латте", price: "1 300 ₸" },
    { name: "Флэт уайт", price: "1 400 ₸" },
    { name: "Раф", price: "1 500 ₸" },
    { name: "Матча латте", price: "1 600 ₸" },
    { name: "Какао", price: "1 300 ₸" },
    { name: "Айс-латте", price: "1 500 ₸" },
    { name: "Айс-американо", price: "1 000 ₸" },
    { name: "Фильтр-кофе", price: "1 100 ₸" },
    { name: "Чай листовой (чайник)", price: "1 800 ₸" },
    { name: "Лимонад домашний", price: "1 400 ₸" },
    { name: "Круассан классический", price: "1 100 ₸" },
    { name: "Круассан с миндалём", price: "1 400 ₸" },
    { name: "Синнабон", price: "1 600 ₸" },
    { name: "Чизкейк", price: "1 900 ₸" },
    { name: "Тирамису", price: "2 000 ₸" },
    { name: "Медовик", price: "1 700 ₸" },
    { name: "Десерт дня", price: "1 800 ₸" },
    { name: "Сэндвич с ветчиной и сыром", price: "2 200 ₸" },
    { name: "Круассан-сэндвич", price: "2 400 ₸" },
    { name: "Гранола с йогуртом", price: "2 100 ₸" },
    { name: "Яичница с тостом", price: "2 300 ₸" },
    { name: "Авокадо-тост", price: "2 600 ₸" },
    { name: "Овсянка на завтрак", price: "1 900 ₸" },
    { name: "Свежевыжатый сок", price: "1 800 ₸" },
    { name: "Зерновой кофе на вынос (250 г)", price: "4 500 ₸" },
  ],
  restaurant: [
    { name: "Бизнес-ланч", price: "3 500 ₸" },
    { name: "Салат Цезарь", price: "3 200 ₸" },
    { name: "Салат с креветками", price: "4 200 ₸" },
    { name: "Овощной салат", price: "2 400 ₸" },
    { name: "Крем-суп дня", price: "2 200 ₸" },
    { name: "Борщ", price: "2 400 ₸" },
    { name: "Стейк из говядины", price: "8 500 ₸" },
    { name: "Лосось на гриле", price: "7 500 ₸" },
    { name: "Паста карбонара", price: "3 800 ₸" },
    { name: "Ризотто с грибами", price: "3 900 ₸" },
    { name: "Пицца Маргарита", price: "3 500 ₸" },
    { name: "Пицца с пепперони", price: "4 000 ₸" },
    { name: "Плов по-домашнему", price: "3 200 ₸" },
    { name: "Манты", price: "2 800 ₸" },
    { name: "Бешбармак", price: "4 500 ₸" },
    { name: "Бургер классический", price: "3 400 ₸" },
    { name: "Куриные крылья", price: "2 900 ₸" },
    { name: "Десерт Наполеон", price: "1 900 ₸" },
    { name: "Чизкейк Нью-Йорк", price: "2 100 ₸" },
    { name: "Мороженое (2 шарика)", price: "1 400 ₸" },
    { name: "Морс домашний", price: "1 200 ₸" },
    { name: "Свежевыжатый сок", price: "1 600 ₸" },
    { name: "Чайник чая", price: "1 800 ₸" },
    { name: "Капучино", price: "1 200 ₸" },
    { name: "Бокал вина", price: "2 500 ₸" },
    { name: "Комплексный ужин на двоих", price: "16 000 ₸" },
  ],
  perfume: [
    { name: "Дизайнерский аромат, 50 мл", price: "28 000 ₸" },
    { name: "Дизайнерский аромат, 100 мл", price: "42 000 ₸" },
    { name: "Нишевый парфюм, 50 мл", price: "45 000 ₸" },
    { name: "Нишевый парфюм, 100 мл", price: "78 000 ₸" },
    { name: "Селектив, 100 мл", price: "65 000 ₸" },
    { name: "Арабская парфюмерия, 100 мл", price: "38 000 ₸" },
    { name: "Мини-версия, 15 мл", price: "12 000 ₸" },
    { name: "Дорожный набор (3×15 мл)", price: "18 000 ₸" },
    { name: "Подарочный набор", price: "35 000 ₸" },
    { name: "Пробник / распив, 5 мл", price: "3 000 ₸" },
    { name: "Автопарфюм", price: "4 500 ₸" },
    { name: "Ароматизатор для дома", price: "9 000 ₸" },
    { name: "Свеча ароматическая", price: "7 500 ₸" },
    { name: "Подбор аромата с консультантом", price: "бесплатно" },
  ],
  shop: [
    { name: "Футболка базовая", price: "6 000 ₸" },
    { name: "Базовый верх / лонгслив", price: "9 000 ₸" },
    { name: "Рубашка", price: "14 000 ₸" },
    { name: "Свитшот / худи", price: "16 000 ₸" },
    { name: "Джинсы", price: "18 000 ₸" },
    { name: "Брюки классические", price: "17 000 ₸" },
    { name: "Платье", price: "22 000 ₸" },
    { name: "Юбка", price: "14 000 ₸" },
    { name: "Костюм двойка", price: "45 000 ₸" },
    { name: "Куртка демисезонная", price: "35 000 ₸" },
    { name: "Пуховик", price: "55 000 ₸" },
    { name: "Пальто", price: "48 000 ₸" },
    { name: "Кроссовки", price: "28 000 ₸" },
    { name: "Ботинки", price: "32 000 ₸" },
    { name: "Туфли", price: "26 000 ₸" },
    { name: "Сумка", price: "20 000 ₸" },
    { name: "Ремень кожаный", price: "8 000 ₸" },
    { name: "Шарф / платок", price: "6 500 ₸" },
    { name: "Головной убор", price: "5 000 ₸" },
    { name: "Носки (набор 3 пары)", price: "3 500 ₸" },
  ],
  fitness: [
    { name: "Разовое занятие", price: "3 000 ₸" },
    { name: "Пробное занятие", price: "бесплатно" },
    { name: "Абонемент на 8 занятий", price: "16 000 ₸" },
    { name: "Абонемент на месяц (безлимит)", price: "20 000 ₸" },
    { name: "Абонемент на 3 месяца", price: "52 000 ₸" },
    { name: "Годовой абонемент", price: "150 000 ₸" },
    { name: "Персональная тренировка", price: "8 000 ₸" },
    { name: "Пакет из 5 персональных тренировок", price: "36 000 ₸" },
    { name: "Групповые классы (разовое)", price: "3 500 ₸" },
    { name: "Йога", price: "3 000 ₸" },
    { name: "Пилатес", price: "3 500 ₸" },
    { name: "Кроссфит", price: "4 000 ₸" },
    { name: "Функциональный тренинг", price: "3 800 ₸" },
    { name: "Сплит, 12 занятий", price: "60 000 ₸" },
    { name: "Составление программы питания", price: "15 000 ₸" },
  ],
  dental: [
    { name: "Консультация", price: "3 000 ₸" },
    { name: "Панорамный снимок", price: "5 000 ₸" },
    { name: "Профессиональная чистка", price: "18 000 ₸" },
    { name: "Гигиена + Air Flow", price: "22 000 ₸" },
    { name: "Лечение кариеса", price: "20 000 ₸" },
    { name: "Лечение пульпита", price: "35 000 ₸" },
    { name: "Удаление зуба", price: "12 000 ₸" },
    { name: "Удаление зуба мудрости", price: "25 000 ₸" },
    { name: "Пломбирование канала", price: "18 000 ₸" },
    { name: "Отбеливание Zoom", price: "60 000 ₸" },
    { name: "Виниры (1 шт.)", price: "от 90 000 ₸" },
    { name: "Коронка керамическая", price: "от 80 000 ₸" },
    { name: "Имплантация", price: "от 250 000 ₸" },
    { name: "Брекет-система", price: "от 350 000 ₸" },
    { name: "Элайнеры (капы)", price: "от 400 000 ₸" },
    { name: "Детский приём", price: "8 000 ₸" },
  ],
  construction: [
    { name: "Выезд и замер", price: "бесплатно" },
    { name: "Дизайн-проект", price: "от 5 000 ₸/м²" },
    { name: "Демонтажные работы", price: "от 3 000 ₸/м²" },
    { name: "Электромонтаж", price: "от 8 000 ₸/м²" },
    { name: "Сантехнические работы", price: "от 7 000 ₸/м²" },
    { name: "Стяжка пола", price: "от 4 500 ₸/м²" },
    { name: "Черновая отделка", price: "от 25 000 ₸/м²" },
    { name: "Чистовая отделка", price: "от 45 000 ₸/м²" },
    { name: "Укладка плитки", price: "от 6 000 ₸/м²" },
    { name: "Укладка ламината", price: "от 3 500 ₸/м²" },
    { name: "Натяжные потолки", price: "от 4 000 ₸/м²" },
    { name: "Ремонт под ключ", price: "от 90 000 ₸/м²" },
    { name: "Строительство дома", price: "договорная" },
    { name: "Авторский надзор", price: "от 150 000 ₸" },
  ],
  auto: [
    { name: "Диагностика", price: "3 000 ₸" },
    { name: "Компьютерная диагностика", price: "5 000 ₸" },
    { name: "Замена масла", price: "8 000 ₸" },
    { name: "Замена фильтров", price: "5 000 ₸" },
    { name: "Развал-схождение", price: "12 000 ₸" },
    { name: "Замена колодок (ось)", price: "15 000 ₸" },
    { name: "Замена тормозных дисков", price: "20 000 ₸" },
    { name: "Шиномонтаж (комплект)", price: "6 000 ₸" },
    { name: "Балансировка колёс", price: "4 000 ₸" },
    { name: "Замена ремня ГРМ", price: "35 000 ₸" },
    { name: "Замена аккумулятора", price: "8 000 ₸" },
    { name: "Заправка кондиционера", price: "10 000 ₸" },
    { name: "Полировка кузова", price: "25 000 ₸" },
    { name: "Химчистка салона", price: "20 000 ₸" },
    { name: "ТО по регламенту", price: "от 20 000 ₸" },
  ],
  generic: [
    { name: "Базовая услуга", price: "от 5 000 ₸" },
    { name: "Стандартный пакет", price: "от 15 000 ₸" },
    { name: "Расширенный пакет", price: "от 30 000 ₸" },
    { name: "Индивидуальное решение", price: "по запросу" },
  ],
} satisfies Record<string, ConceptService[]>;

// First match wins — specific niches before broad ones (mirrors concept-images matching).
const MATCHERS: Array<[keyof typeof CATALOGS, string[]]> = [
  ["dental", ["стоматолог", "зуб", "дент", "dental", "ортодонт", "denta"]],
  ["barbershop", ["барбер", "стрижк", "бород"]],
  ["perfume", ["парфюм", "аромат", "sillage", "духи"]],
  ["beauty", ["салон", "красот", "маникюр", "ногт", "бров", "ресниц", "космет", "spa", "спа", "визаж", "макияж", "lumi"]],
  ["coffee", ["кофе", "кофейн", "roast", "бариста"]],
  ["restaurant", ["ресторан", "кафе", "бар", "пицц", "суши", "кухн", "еда", "food", "north"]],
  ["fitness", ["фитнес", "зал", "спорт", "трен", "gym", "fitness", "йога", "pulse"]],
  ["construction", ["строит", "строительн", "ремонт", "монолит", "monolith", "прораб", "отделк", "construct"]],
  ["auto", ["сто", "автосервис", "автосалон", "шином", "детейлинг", "ремонт авто", "ремонт машин", "auto", "car service"]],
  ["shop", ["магазин", "товар", "одежд", "бутик", "shop", "store", "маркет"]],
];

export function conceptServicesFor(businessType: string): ConceptServiceCatalog {
  const normalized = businessType.toLowerCase();
  for (const [key, keywords] of MATCHERS) {
    if (keywords.some((word) => normalized.includes(word))) return { items: CATALOGS[key], note: NOTE };
  }
  return { items: CATALOGS.generic, note: NOTE };
}
