"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import type { AnalysisResult, EstimateForm, EstimateResult } from "@/components/site-experience";
import type { ConceptColorId, ConceptStyleId, WebsiteConcept } from "@/lib/website-concept";
import { projectRepository } from "./project-repository";
import {
  generationStages,
  runProjectGeneration,
  type GenerationStageId,
  type ProjectBrief,
} from "./project-generation";

/**
 * The central object of the Workspace. A Project is one business worked on end-to-end: the AI
 * Consultant's analysis, the Design Studio's concept (which already carries its own selected
 * colors/style — see WebsiteConcept), and the Pricing calculator's form + result all live on the
 * SAME project instead of each tool inventing its own disconnected "saved item". There is no
 * separate `workflow` field: the workflow map is `analysis.flow`, already generated by the AI
 * Consultant — storing it twice would just be two copies that can drift apart.
 */
/** One exchange with the AI Designer: what was asked, what actually changed, and what it
 * suggested next. Stored so a later request can build on earlier decisions instead of treating
 * every edit as an isolated one-off. */
export type DesignerEntry = {
  id: string;
  at: number;
  request: string;
  /** Human-readable summary of the concrete changes applied. */
  changes: string[];
  /** Which part of the project the edit landed on, for the history list. */
  section: string;
  /** The follow-up the designer offered, if it had one worth making. */
  suggestion: string | null;
};

export type ProjectPricing = {
  form: EstimateForm;
  result: EstimateResult;
};

export type Project = {
  id: string;
  name: string;
  /** Free text — may come from the Create Project form's category or from the Hero's detected
   * business label, so it's a plain string rather than either union type. */
  businessType: string;
  /** The original free-text description that seeded this project. */
  businessDescription: string;
  city: string;
  /** 1-3 visual styles chosen from the briefing's style cards — one of the AI's inputs, and kept
   * so the Overview can show what the project was asked for. */
  preferredStyleIds: ConceptStyleId[];
  preferredColorIds: ConceptColorId[];
  /** When the automatic first generation finished. Null while a project has never been generated
   * (only possible for projects created before this flow existed). */
  generatedAt: number | null;
  /** Set when the owner publishes; the only lifecycle state that is stored rather than derived. */
  publishedAt: number | null;
  /**
   * This project's own AI Designer history. Scoped to the project on purpose: a later
   * account-wide memory layer sits ABOVE this one (account → project → session) and must never
   * be able to leak one client's design decisions into another's project.
   */
  designerLog: DesignerEntry[];
  createdAt: number;
  updatedAt: number;
  analysis: AnalysisResult | null;
  design: WebsiteConcept | null;
  pricing: ProjectPricing | null;
};

export type CreateProjectInput = {
  name: string;
  businessType: string;
  businessDescription: string;
  city?: string;
  preferredStyleIds?: ConceptStyleId[];
  preferredColorIds?: ConceptColorId[];
};

/**
 * Deliberately NOT a stored field on Project — completion state is derived from what's actually
 * there, so it can never drift out of sync with the real content the way a cached `status`
 * string could.
 */
export type ProjectProgress = {
  hasAnalysis: boolean;
  hasDesign: boolean;
  hasWorkflow: boolean;
  hasPricing: boolean;
  completedCount: number;
  totalCount: number;
};

export function getProjectProgress(project: Project): ProjectProgress {
  const hasAnalysis = Boolean(project.analysis);
  const hasDesign = Boolean(project.design);
  const hasWorkflow = Boolean(project.analysis?.flow.length);
  const hasPricing = Boolean(project.pricing);
  const flags = [hasAnalysis, hasDesign, hasPricing];
  return {
    hasAnalysis,
    hasDesign,
    hasWorkflow,
    hasPricing,
    completedCount: flags.filter(Boolean).length,
    totalCount: flags.length,
  };
}

export type ProjectStatus = {
  id: "generating" | "new" | "ready" | "edited" | "published";
  label: string;
};

/**
 * The project's lifecycle: Generating → Ready → Edited → Published.
 *
 * Only `published` is stored, because it is the one transition a person performs deliberately.
 * Everything else is derived from facts already on the project — whether a run is in flight,
 * whether the sections exist, and whether anything was touched after the first generation — so
 * the badge can never disagree with the project's real state the way a cached string would.
 */
export function getProjectStatus(project: Project, generatingId?: string | null): ProjectStatus {
  if (generatingId === project.id) return { id: "generating", label: "Генерация" };
  if (project.publishedAt) return { id: "published", label: "Опубликован" };
  const progress = getProjectProgress(project);
  if (progress.completedCount === 0) return { id: "new", label: "Новый" };
  // A second of tolerance: the generation write and its own `updatedAt` land together.
  if (project.generatedAt && project.updatedAt > project.generatedAt + 1000) {
    return { id: "edited", label: "Изменён" };
  }
  if (progress.completedCount < progress.totalCount) return { id: "new", label: "Черновик" };
  return { id: "ready", label: "Готов" };
}

/** "saving" flashes briefly on every change, then settles on "saved" — the topbar indicator. */
export type SaveState = "idle" | "saving" | "saved";

/** Which project is currently generating, and how far along. Lives on the provider (mounted in
 * the root layout) rather than in a page component, so navigating from the briefing straight to
 * the project does not abort the run that navigation was triggered by. */
export type GenerationState = {
  projectId: string;
  stage: GenerationStageId;
  /** Only the sections being (re)generated — a full first run lists all of them. */
  scope: GenerationScope[];
} | null;

export type GenerationScope = "analysis" | "design" | "pricing";

type ProjectsContextValue = {
  projects: Project[];
  /** False until the initial localStorage read completes — lets a consumer distinguish "still
   * loading" from "genuinely no projects" (the empty state waits for this). */
  isLoaded: boolean;
  saveState: SaveState;
  create: (input: CreateProjectInput) => Project;
  rename: (id: string, name: string) => void;
  duplicate: (id: string) => Project | null;
  remove: (id: string) => void;
  getProject: (id: string) => Project | null;
  saveAnalysis: (id: string, analysis: AnalysisResult) => void;
  saveDesign: (id: string, design: WebsiteConcept) => void;
  savePricing: (id: string, pricing: ProjectPricing) => void;
  /** Appends one AI Designer exchange to this project's own memory. */
  appendDesignerEntry: (id: string, entry: DesignerEntry) => void;
  /** Records the pre-edit design so the change can be reverted. Call before saveDesign. */
  pushHistory: (id: string, previous: WebsiteConcept | null) => void;
  undo: (id: string) => void;
  redo: (id: string) => void;
  canUndo: (id: string) => boolean;
  canRedo: (id: string) => boolean;
  /** Marks the project published — the one lifecycle state a person sets deliberately. */
  publish: (id: string) => void;
  generation: GenerationState;
  /** Runs the full first generation for a freshly created project. */
  generateAll: (project: Project) => Promise<void>;
  /** Regenerates ONE section, leaving the other two untouched. */
  regenerate: (project: Project, scope: GenerationScope) => Promise<void>;
};

const ProjectsContext = createContext<ProjectsContextValue | null>(null);

function createId() {
  return typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `project-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
}

function touch<T extends { updatedAt: number }>(project: T): T {
  return { ...project, updatedAt: Date.now() };
}

/**
 * Persists through `projectRepository` (localStorage today, swappable for a real backend later
 * without touching any page — every consumer goes through `useProjects()`).
 *
 * Hydration safety: initial state is always `[]`, identical on server and first client render.
 * The real data (if any) loads one tick later in an effect that never runs during SSR, so the
 * only thing that changes post-hydration is a normal state update — never a server/client
 * mismatch.
 */
export function ProjectsProvider({ children }: { children: ReactNode }) {
  const [projects, setProjects] = useState<Project[]>([]);
  const [isLoaded, setIsLoaded] = useState(false);
  const [saveState, setSaveState] = useState<SaveState>("idle");
  const [generation, setGeneration] = useState<GenerationState>(null);
  const abortRef = useRef<AbortController | null>(null);

  useEffect(() => {
    setProjects(projectRepository.load());
    setIsLoaded(true);
  }, []);

  // Skip the very first run (before the load above has happened) so it can't stomp real stored
  // data with the initial empty array. The write itself is synchronous; the short "saving"
  // window exists so the indicator visibly reacts to every change.
  useEffect(() => {
    if (!isLoaded) return;
    setSaveState("saving");
    projectRepository.save(projects);
    const timer = setTimeout(() => setSaveState("saved"), 350);
    return () => clearTimeout(timer);
  }, [projects, isLoaded]);

  const create = useCallback((input: CreateProjectInput) => {
    const now = Date.now();
    const project: Project = {
      id: createId(),
      name: input.name.trim() || "Новый проект",
      businessType: input.businessType,
      businessDescription: input.businessDescription,
      city: input.city ?? "",
      preferredStyleIds: input.preferredStyleIds ?? [],
      preferredColorIds: input.preferredColorIds ?? [],
      generatedAt: null,
      publishedAt: null,
      designerLog: [],
      createdAt: now,
      updatedAt: now,
      analysis: null,
      design: null,
      pricing: null,
    };
    setProjects((current) => [project, ...current]);
    return project;
  }, []);

  const rename = useCallback((id: string, name: string) => {
    const trimmed = name.trim();
    if (!trimmed) return;
    setProjects((current) => current.map((project) => (project.id === id ? touch({ ...project, name: trimmed }) : project)));
  }, []);

  const duplicate = useCallback(
    (id: string) => {
      const source = projects.find((project) => project.id === id);
      if (!source) return null;
      const now = Date.now();
      const copy: Project = { ...source, id: createId(), name: `${source.name} (копия)`, createdAt: now, updatedAt: now };
      setProjects((current) => [copy, ...current]);
      return copy;
    },
    [projects],
  );

  const remove = useCallback((id: string) => {
    setProjects((current) => current.filter((project) => project.id !== id));
  }, []);

  const getProject = useCallback((id: string) => projects.find((project) => project.id === id) ?? null, [projects]);

  const saveAnalysis = useCallback((id: string, analysis: AnalysisResult) => {
    setProjects((current) => current.map((project) => (project.id === id ? touch({ ...project, analysis }) : project)));
  }, []);

  const saveDesign = useCallback((id: string, design: WebsiteConcept) => {
    setProjects((current) => current.map((project) => (project.id === id ? touch({ ...project, design }) : project)));
  }, []);

  const savePricing = useCallback((id: string, pricing: ProjectPricing) => {
    setProjects((current) => current.map((project) => (project.id === id ? touch({ ...project, pricing }) : project)));
  }, []);

  /**
   * Undo/redo for AI edits.
   *
   * Snapshots live in a ref rather than in the project itself: a full concept is a large object,
   * and writing every intermediate state to localStorage would bloat storage for a stack whose
   * whole purpose is to be transient. The consequence — history is per session and resets on
   * reload — is the deliberate trade, and the saved project is always the committed state.
   */
  const historyRef = useRef<Map<string, { past: (WebsiteConcept | null)[]; future: (WebsiteConcept | null)[] }>>(new Map());
  // Refs don't re-render, but the Undo/Redo buttons must enable and disable as the stack moves.
  const [, bumpHistory] = useState(0);

  const stackFor = (id: string) => {
    let stack = historyRef.current.get(id);
    if (!stack) {
      stack = { past: [], future: [] };
      historyRef.current.set(id, stack);
    }
    return stack;
  };

  const pushHistory = useCallback((id: string, previous: WebsiteConcept | null) => {
    const stack = stackFor(id);
    // A new edit invalidates anything that was undone — the classic branch-and-drop.
    stack.past.push(previous);
    stack.future = [];
    if (stack.past.length > 30) stack.past.shift();
    bumpHistory((value) => value + 1);
  }, []);

  /**
   * The stack is moved BEFORE setProjects, never inside its updater. React intentionally invokes
   * updater functions twice in development, so a pop() in there ran twice and undid two steps on
   * the first click — updaters must stay pure.
   */
  const undo = useCallback((id: string) => {
    const stack = stackFor(id);
    if (!stack.past.length) return;
    const previous = stack.past.pop() ?? null;
    let reverted = false;
    setProjects((current) =>
      current.map((project) => {
        if (project.id !== id) return project;
        if (!reverted) {
          stack.future.push(project.design);
          reverted = true;
        }
        return touch({ ...project, design: previous });
      }),
    );
    bumpHistory((value) => value + 1);
  }, []);

  const redo = useCallback((id: string) => {
    const stack = stackFor(id);
    if (!stack.future.length) return;
    const next = stack.future.pop() ?? null;
    let restored = false;
    setProjects((current) =>
      current.map((project) => {
        if (project.id !== id) return project;
        if (!restored) {
          stack.past.push(project.design);
          restored = true;
        }
        return touch({ ...project, design: next });
      }),
    );
    bumpHistory((value) => value + 1);
  }, []);

  const canUndo = useCallback((id: string) => Boolean(historyRef.current.get(id)?.past.length), []);
  const canRedo = useCallback((id: string) => Boolean(historyRef.current.get(id)?.future.length), []);

  const appendDesignerEntry = useCallback((id: string, entry: DesignerEntry) => {
    setProjects((current) =>
      current.map((project) =>
        // Capped so a long-lived project cannot grow its stored history without bound; the most
        // recent decisions are the ones later requests need.
        project.id === id ? touch({ ...project, designerLog: [...project.designerLog, entry].slice(-40) }) : project,
      ),
    );
  }, []);

  const publish = useCallback((id: string) => {
    setProjects((current) =>
      current.map((project) => (project.id === id ? touch({ ...project, publishedAt: Date.now() }) : project)),
    );
  }, []);

  const briefFor = (project: Project): ProjectBrief => ({
    name: project.name,
    businessType: project.businessType,
    city: project.city,
    description: project.businessDescription,
    styleIds: project.preferredStyleIds,
    colorIds: project.preferredColorIds,
  });

  const run = useCallback(async (project: Project, scope: GenerationScope[]) => {
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;
    setGeneration({ projectId: project.id, stage: generationStages[0].id, scope });

    try {
      const result = await runProjectGeneration(
        briefFor(project),
        (stage) => setGeneration((current) => (current ? { ...current, stage } : current)),
        controller.signal,
      );
      // Written in one update so a project never exists in a half-generated state on disk.
      setProjects((current) =>
        current.map((item) =>
          item.id === project.id
            ? touch({
                ...item,
                analysis: scope.includes("analysis") ? result.analysis ?? item.analysis : item.analysis,
                design: scope.includes("design") ? result.design ?? item.design : item.design,
                pricing: scope.includes("pricing") ? result.pricing ?? item.pricing : item.pricing,
                generatedAt: item.generatedAt ?? Date.now(),
              })
            : item,
        ),
      );
    } finally {
      if (abortRef.current === controller) abortRef.current = null;
      setGeneration(null);
    }
  }, []);

  const generateAll = useCallback(
    (project: Project) => run(project, ["analysis", "design", "pricing"]),
    [run],
  );

  const regenerate = useCallback(
    (project: Project, scope: GenerationScope) => run(project, [scope]),
    [run],
  );

  const value = useMemo<ProjectsContextValue>(
    () => ({
      projects,
      isLoaded,
      saveState,
      create,
      rename,
      duplicate,
      remove,
      getProject,
      saveAnalysis,
      saveDesign,
      savePricing,
      appendDesignerEntry,
      pushHistory,
      undo,
      redo,
      canUndo,
      canRedo,
      publish,
      generation,
      generateAll,
      regenerate,
    }),
    [projects, isLoaded, saveState, create, rename, duplicate, remove, getProject, saveAnalysis, saveDesign, savePricing, appendDesignerEntry, pushHistory, undo, redo, canUndo, canRedo, publish, generation, generateAll, regenerate],
  );

  return <ProjectsContext.Provider value={value}>{children}</ProjectsContext.Provider>;
}

export function useProjects() {
  const value = useContext(ProjectsContext);
  if (!value) throw new Error("useProjects must be used within a ProjectsProvider");
  return value;
}
