"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import type { AnalysisResult, EstimateForm, EstimateResult } from "@/components/site-experience";
import type { ConceptColorId, ConceptGoal, ConceptSectionType, ConceptStyleId, WebsiteConcept } from "@/lib/website-concept";
import { useAuth } from "./auth-context";
import {
  clearLocalProjectsAfterMigration,
  readLocalProjectsForMigration,
  serverProjectStore,
  storeFor,
} from "./project-repository";
import {
  generationStages,
  runProjectGeneration,
  type GenerationStageId,
  type ProjectBrief,
} from "./project-generation";

/**
 * The central object of the Workspace. A Project is one business worked on end-to-end: the AI
 * Consultant's analysis, the Design Studio's concept (which already carries its own selected
 * colors/style — see WebsiteConcept), and the Pricing calculator's form + result all live on the
 * SAME project instead of each tool inventing its own disconnected "saved item". There is no
 * separate `workflow` field: the workflow map is `analysis.flow`, already generated by the AI
 * Consultant — storing it twice would just be two copies that can drift apart.
 */
/** One exchange with the AI Designer: what was asked, what actually changed, and what it
 * suggested next. Stored so a later request can build on earlier decisions instead of treating
 * every edit as an isolated one-off. */
export type DesignerEntry = {
  id: string;
  at: number;
  request: string;
  /** Human-readable summary of the concrete changes applied. */
  changes: string[];
  /** Which part of the project the edit landed on, for the history list. */
  section: string;
  /** The follow-up the designer offered, if it had one worth making. */
  suggestion: string | null;
};

/**
 * One reversible step, stored as the FIELDS that changed rather than a full concept snapshot.
 * A designer edit touches a palette, a style, a layout, a page or one price — keeping only those
 * keeps the stack small enough to persist with the project instead of dying with the tab.
 */
export type ConceptDiff = Partial<Pick<WebsiteConcept, "colorIds" | "styleId" | "layoutId" | "offers" | "pages">>;

const DIFF_KEYS = ["colorIds", "styleId", "layoutId", "offers", "pages"] as const;

/** The fields of `from` that differ from `to` — i.e. what to write to get back to `from`. */
export function conceptDiff(from: WebsiteConcept | null, to: WebsiteConcept | null): ConceptDiff {
  if (!from) return {};
  const diff: ConceptDiff = {};
  for (const key of DIFF_KEYS) {
    if (!to || JSON.stringify(from[key]) !== JSON.stringify(to[key])) {
      Object.assign(diff, { [key]: from[key] });
    }
  }
  return diff;
}

export function applyConceptDiff(design: WebsiteConcept | null, diff: ConceptDiff): WebsiteConcept | null {
  if (!design) return design;
  return { ...design, ...diff };
}

export type ProjectPricing = {
  form: EstimateForm;
  result: EstimateResult;
};

export type Project = {
  id: string;
  name: string;
  /** Free text — may come from the Create Project form's category or from the Hero's detected
   * business label, so it's a plain string rather than either union type. */
  businessType: string;
  /** The original free-text description that seeded this project. */
  businessDescription: string;
  city: string;
  /** 1-3 visual styles chosen from the briefing's style cards — one of the AI's inputs, and kept
   * so the Overview can show what the project was asked for. */
  preferredStyleIds: ConceptStyleId[];
  preferredColorIds: ConceptColorId[];
  /**
   * Задача сайта и набор разделов — то, что мастер на лендинге спрашивал, а Workspace нет.
   * Пустой массив означает проект, созданный до того, как их начали спрашивать: генерация в
   * этом случае берёт свои прежние умолчания, а не падает.
   *
   * Задача — не украшение брифа: от неё зависит, потребует ли маршрут концепта секцию записи
   * или секцию цен. Пока её зашивали в «Получать заявки», каждый проект из Workspace строился
   * под заявки, даже когда бизнесу нужна запись.
   */
  goals: ConceptGoal[];
  /**
   * Подтверждённая человеком структура сайта: упорядоченный список разделов с названиями.
   *
   * Раньше это был просто набор галочек `ConceptSectionType[]`. Порядок и название появились,
   * когда мастер стал предлагать структуру, а человек — её править: без них «переставить» и
   * «переименовать» были бы обманом, правка не пережила бы сохранение.
   *
   * Старая форма (массив строк) читается нормализацией как прежде — см. project-schema.
   */
  sections: ProjectSection[];
  /** Свободные пожелания к характеру сайта — уходят в запрос к модели как есть. */
  wishes: string;
  /** When the automatic first generation finished. Null while a project has never been generated
   * (only possible for projects created before this flow existed). */
  generatedAt: number | null;
  /** Set when the owner publishes; the only lifecycle state that is stored rather than derived. */
  publishedAt: number | null;
  /**
   * This project's own AI Designer history. Scoped to the project on purpose: a later
   * account-wide memory layer sits ABOVE this one (account → project → session) and must never
   * be able to leak one client's design decisions into another's project.
   */
  designerLog: DesignerEntry[];
  /** Undo stack, oldest first. Each entry restores the state before one edit. */
  editHistory: ConceptDiff[];
  /** Redo stack, populated as steps are undone. */
  redoHistory: ConceptDiff[];
  createdAt: number;
  updatedAt: number;
  analysis: AnalysisResult | null;
  design: WebsiteConcept | null;
  pricing: ProjectPricing | null;
};

/** Один раздел подтверждённой структуры. */
export type ProjectSection = { type: ConceptSectionType; title: string };

export type CreateProjectInput = {
  name: string;
  businessType: string;
  businessDescription: string;
  city?: string;
  preferredStyleIds?: ConceptStyleId[];
  preferredColorIds?: ConceptColorId[];
  goals?: ConceptGoal[];
  sections?: ProjectSection[];
  wishes?: string;
};

/**
 * Deliberately NOT a stored field on Project — completion state is derived from what's actually
 * there, so it can never drift out of sync with the real content the way a cached `status`
 * string could.
 */
export type ProjectProgress = {
  hasAnalysis: boolean;
  hasDesign: boolean;
  hasWorkflow: boolean;
  hasPricing: boolean;
  completedCount: number;
  totalCount: number;
};

export function getProjectProgress(project: Project): ProjectProgress {
  const hasAnalysis = Boolean(project.analysis);
  const hasDesign = Boolean(project.design);
  const hasWorkflow = Boolean(project.analysis?.flow.length);
  const hasPricing = Boolean(project.pricing);
  const flags = [hasAnalysis, hasDesign, hasPricing];
  return {
    hasAnalysis,
    hasDesign,
    hasWorkflow,
    hasPricing,
    completedCount: flags.filter(Boolean).length,
    totalCount: flags.length,
  };
}

export type ProjectStatus = {
  id: "generating" | "new" | "ready" | "edited" | "published";
  label: string;
};

/**
 * The project's lifecycle: Generating → Ready → Edited → Published.
 *
 * Only `published` is stored, because it is the one transition a person performs deliberately.
 * Everything else is derived from facts already on the project — whether a run is in flight,
 * whether the sections exist, and whether anything was touched after the first generation — so
 * the badge can never disagree with the project's real state the way a cached string would.
 */
export function getProjectStatus(project: Project, generatingId?: string | null): ProjectStatus {
  if (generatingId === project.id) return { id: "generating", label: "Генерация" };
  if (project.publishedAt) return { id: "published", label: "Опубликован" };
  const progress = getProjectProgress(project);
  if (progress.completedCount === 0) return { id: "new", label: "Новый" };
  // A second of tolerance: the generation write and its own `updatedAt` land together.
  if (project.generatedAt && project.updatedAt > project.generatedAt + 1000) {
    return { id: "edited", label: "Изменён" };
  }
  if (progress.completedCount < progress.totalCount) return { id: "new", label: "Черновик" };
  return { id: "ready", label: "Готов" };
}

/** "saving" flashes briefly on every change, then settles on "saved" — the topbar indicator.
 * "error" появился вместе с сервером: запись по сети, в отличие от записи в localStorage,
 * умеет не удаваться, и молчать об этом нельзя — человек продолжит работать, считая, что всё
 * сохранено. */
export type SaveState = "idle" | "saving" | "saved" | "error";

/** Which project is currently generating, and how far along. Lives on the provider (mounted in
 * the root layout) rather than in a page component, so navigating from the briefing straight to
 * the project does not abort the run that navigation was triggered by. */
export type GenerationState = {
  projectId: string;
  stage: GenerationStageId;
  /** Only the sections being (re)generated — a full first run lists all of them. */
  scope: GenerationScope[];
} | null;

export type GenerationScope = "analysis" | "design" | "pricing";

type ProjectsContextValue = {
  projects: Project[];
  /** False until the initial localStorage read completes — lets a consumer distinguish "still
   * loading" from "genuinely no projects" (the empty state waits for this). */
  isLoaded: boolean;
  saveState: SaveState;
  retrySave: () => void;
  /** Куда пишутся проекты прямо сейчас. Список проектов показывает по этому полю, лежит ли
   * работа в аккаунте или всё ещё только на этом устройстве. */
  storage: "device" | "account";
  /** Заполняется, если проекты аккаунта не удалось прочитать. Пока оно не null, приложение
   * НИЧЕГО не сохраняет: записать пустой список поверх сервера значило бы стереть работу. */
  loadError: string | null;
  /** Заполняется, если перенос локальных проектов в аккаунт не удался. Локальная копия при
   * этом остаётся нетронутой. */
  migrationError: string | null;
  create: (input: CreateProjectInput) => Project;
  rename: (id: string, name: string) => void;
  duplicate: (id: string) => Project | null;
  remove: (id: string) => void;
  getProject: (id: string) => Project | null;
  saveAnalysis: (id: string, analysis: AnalysisResult) => void;
  saveDesign: (id: string, design: WebsiteConcept) => void;
  savePricing: (id: string, pricing: ProjectPricing) => void;
  /** Appends one AI Designer exchange to this project's own memory. */
  appendDesignerEntry: (id: string, entry: DesignerEntry) => void;
  /** Records a reversible step. Both sides are required: the diff is computed between them, and
   * at call time the project still holds `previous`, so it cannot be derived from state. */
  pushHistory: (id: string, previous: WebsiteConcept | null, next: WebsiteConcept | null) => void;
  undo: (id: string) => void;
  redo: (id: string) => void;
  canUndo: (id: string) => boolean;
  canRedo: (id: string) => boolean;
  /** Marks the project published — the one lifecycle state a person sets deliberately. */
  publish: (id: string) => void;
  /** Returns a published project to the editable states, so publishing is not a one-way door. */
  unpublish: (id: string) => void;
  generation: GenerationState;
  /** Runs the full first generation for a freshly created project. */
  generateAll: (project: Project) => Promise<void>;
  /** Regenerates ONE section, leaving the other two untouched. */
  regenerate: (project: Project, scope: GenerationScope) => Promise<void>;
};

const ProjectsContext = createContext<ProjectsContextValue | null>(null);

function createId() {
  return typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `project-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
}

function touch<T extends { updatedAt: number }>(project: T): T {
  return { ...project, updatedAt: Date.now() };
}

/**
 * Persists through `projectRepository` (localStorage today, swappable for a real backend later
 * without touching any page — every consumer goes through `useProjects()`).
 *
 * Hydration safety: initial state is always `[]`, identical on server and first client render.
 * The real data (if any) loads one tick later in an effect that never runs during SSR, so the
 * only thing that changes post-hydration is a normal state update — never a server/client
 * mismatch.
 */
/** Задержка перед отправкой на сервер. Для localStorage запись бесплатна и делается сразу;
 * по сети каждая правка палитры превратилась бы в отдельный запрос. */
const SAVE_DEBOUNCE_MS = 1000;

/**
 * Сливает то, что лежало в браузере, с тем, что уже есть в аккаунте.
 *
 * Совпадение по id возможно: человек мог войти на устройстве, где раньше работал без аккаунта,
 * а тот же проект уже перенесён с другого. Выигрывает более свежая версия — это единственное
 * правило, которое не требует спрашивать человека и не теряет более новую работу.
 */
function mergeById(base: Project[], incoming: Project[]): Project[] {
  const byId = new Map(base.map((project) => [project.id, project]));
  for (const project of incoming) {
    const existing = byId.get(project.id);
    if (!existing || project.updatedAt > existing.updatedAt) byId.set(project.id, project);
  }
  return [...byId.values()].sort((a, b) => b.updatedAt - a.updatedAt);
}

export function ProjectsProvider({ children }: { children: ReactNode }) {
  const [projects, setProjects] = useState<Project[]>([]);
  const [isLoaded, setIsLoaded] = useState(false);
  const [saveState, setSaveState] = useState<SaveState>("idle");
  const [retryTick, setRetryTick] = useState(0);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [migrationError, setMigrationError] = useState<string | null>(null);
  const [generation, setGeneration] = useState<GenerationState>(null);
  const abortRef = useRef<AbortController | null>(null);

  const { user, isLoaded: authLoaded } = useAuth();
  const signedIn = Boolean(user);
  const accountId = user?.id ?? null;

  /**
   * Первая загрузка отличается от последующих: она НЕ имеет права затирать то, что человек
   * успел создать, пока она шла.
   *
   * Раньше чтение начиналось сразу при монтировании и завершалось прежде, чем до интерфейса
   * доходили руки. Теперь оно ждёт ответа о состоянии входа, то есть сетевого запроса, — и в
   * это окно помещается создание проекта. Проект в этот момент живёт только в состоянии
   * (сохранение заблокировано до `isLoaded`), поэтому пришедший из хранилища список его не
   * содержит, и простое присваивание стёрло бы работу.
   *
   * Смена аккаунта — другое дело: там присваивание как раз и нужно, иначе проекты предыдущего
   * человека остались бы на экране следующего.
   */
  const firstLoadRef = useRef(true);

  const applyLoaded = useCallback((stored: Project[]) => {
    // Флаг снимается ДО setProjects, а не внутри него. React намеренно вызывает функцию-
    // обновление дважды в разработке, и правка ref внутри неё привела бы к тому, что второй
    // вызов увидел бы флаг уже снятым и вернул `stored`, потеряв созданное. Ровно на этом
    // однажды сломался undo — см. комментарий над ним.
    const isFirst = firstLoadRef.current;
    firstLoadRef.current = false;
    // Слияние только на первой загрузке и только если человек уже что-то создал.
    setProjects((current) => (isFirst && current.length ? mergeById(stored, current) : stored));
  }, []);

  /**
   * Загрузка. Ждёт ответа о состоянии входа: до него неизвестно, у какого хранилища спрашивать,
   * а прочитать не у того — значит показать человеку чужой (пустой) Workspace и следом
   * сохранить эту пустоту.
   *
   * Перезапускается при смене аккаунта: вход и выход обязаны менять содержимое Workspace.
   */
  useEffect(() => {
    if (!authLoaded) return;
    let cancelled = false;
    setIsLoaded(false);
    setLoadError(null);
    setMigrationError(null);

    void (async () => {
      try {
        const stored = await storeFor(signedIn).load();
        if (cancelled) return;

        if (!signedIn) {
          applyLoaded(stored);
          setIsLoaded(true);
          return;
        }

        // Перенос при входе. Порядок из docs/database.md: сначала убедиться, что данные приняты
        // сервером, и только потом убирать их с устройства. Наоборот — значит однажды потерять
        // чужую работу из-за сетевого сбоя.
        const local = await readLocalProjectsForMigration();
        if (cancelled) return;
        if (!local.length) {
          applyLoaded(stored);
          setIsLoaded(true);
          return;
        }

        const merged = mergeById(stored, local);
        try {
          await serverProjectStore.save(merged);
          await clearLocalProjectsAfterMigration();
          if (cancelled) return;
          applyLoaded(merged);
        } catch {
          // Ничего не удалено: локальная копия цела, перенос можно повторить входом заново.
          if (cancelled) return;
          setMigrationError(
            "Проекты с этого устройства не удалось перенести в аккаунт. Они остались здесь — попробуйте войти ещё раз.",
          );
          applyLoaded(stored);
        }
        setIsLoaded(true);
      } catch {
        if (cancelled) return;
        // Сознательно НЕ выставляем isLoaded: пока данные аккаунта не прочитаны, сохранять
        // нечего и опасно — эффект ниже записал бы пустой список поверх реальных проектов.
        setLoadError("Не удалось загрузить проекты аккаунта. Обновите страницу.");
        setSaveState("error");
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [authLoaded, signedIn, accountId, applyLoaded]);

  /**
   * Последнее, что ещё не подтверждено сервером. Нужен для досохранения при закрытии вкладки:
   * задержка перед отправкой создаёт окно, в которое правка живёт только в памяти.
   */
  const pendingRef = useRef<Project[] | null>(null);

  // Skip the very first run (before the load above has happened) so it can't stomp real stored
  // data with the initial empty array.
  useEffect(() => {
    if (!isLoaded) return;
    setSaveState("saving");
    pendingRef.current = projects;
    let cancelled = false;
    const store = storeFor(signedIn);

    const timer = window.setTimeout(() => {
      // The indicator holds "saving" for a beat even when the write is instant, so a change is
      // visibly acknowledged; with a server behind this, the real latency simply takes over.
      const started = Date.now();
      store
        .save(projects)
        .then(() => {
          if (cancelled) return;
          pendingRef.current = null;
          const remaining = Math.max(0, 350 - (Date.now() - started));
          window.setTimeout(() => {
            if (!cancelled) setSaveState("saved");
          }, remaining);
        })
        .catch(() => {
          // Локальная запись не умеет не удаваться, серверная умеет. Показать это обязательно:
          // иначе человек продолжит работать в уверенности, что всё сохранено.
          if (!cancelled) setSaveState("error");
        });
    }, signedIn ? SAVE_DEBOUNCE_MS : 0);

    return () => {
      cancelled = true;
      window.clearTimeout(timer);
    };
    // retryTick в зависимостях: «Повторить» после ошибки переигрывает этот эффект и переотправляет
    // актуальное несинхронизированное состояние.
  }, [projects, isLoaded, signedIn, retryTick]);

  /** Повторить сохранение после ошибки — переотправляет актуальное несинхронизированное состояние. */
  const retrySave = useCallback(() => setRetryTick((tick) => tick + 1), []);

  /**
   * Досохранение при уходе со страницы.
   *
   * `pagehide` вместо `beforeunload`: последний не срабатывает на мобильных при переключении
   * приложения, а это как раз тот случай, когда вкладку больше не увидят. `keepalive`
   * разрешает запросу пережить закрытие документа.
   */
  useEffect(() => {
    if (!signedIn) return;
    const flush = () => {
      const pending = pendingRef.current;
      if (!pending) return;
      pendingRef.current = null;
      // Напрямую, а не через хранилище: keepalive — свойство именно этого, последнего запроса.
      void fetch("/api/projects", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ projects: pending }),
        keepalive: true,
      }).catch(() => {});
    };
    window.addEventListener("pagehide", flush);
    return () => window.removeEventListener("pagehide", flush);
  }, [signedIn]);

  const create = useCallback((input: CreateProjectInput) => {
    const now = Date.now();
    const project: Project = {
      id: createId(),
      name: input.name.trim() || "Новый проект",
      businessType: input.businessType,
      businessDescription: input.businessDescription,
      city: input.city ?? "",
      preferredStyleIds: input.preferredStyleIds ?? [],
      preferredColorIds: input.preferredColorIds ?? [],
      goals: input.goals ?? [],
      sections: input.sections ?? [],
      wishes: input.wishes ?? "",
      generatedAt: null,
      publishedAt: null,
      designerLog: [],
      editHistory: [],
      redoHistory: [],
      createdAt: now,
      updatedAt: now,
      analysis: null,
      design: null,
      pricing: null,
    };
    setProjects((current) => [project, ...current]);
    return project;
  }, []);

  const rename = useCallback((id: string, name: string) => {
    const trimmed = name.trim();
    if (!trimmed) return;
    setProjects((current) => current.map((project) => (project.id === id ? touch({ ...project, name: trimmed }) : project)));
  }, []);

  const duplicate = useCallback(
    (id: string) => {
      const source = projects.find((project) => project.id === id);
      if (!source) return null;
      const now = Date.now();
      const copy: Project = { ...source, id: createId(), name: `${source.name} (копия)`, createdAt: now, updatedAt: now };
      setProjects((current) => [copy, ...current]);
      return copy;
    },
    [projects],
  );

  const remove = useCallback((id: string) => {
    setProjects((current) => current.filter((project) => project.id !== id));
  }, []);

  const getProject = useCallback((id: string) => projects.find((project) => project.id === id) ?? null, [projects]);

  const saveAnalysis = useCallback((id: string, analysis: AnalysisResult) => {
    setProjects((current) => current.map((project) => (project.id === id ? touch({ ...project, analysis }) : project)));
  }, []);

  const saveDesign = useCallback((id: string, design: WebsiteConcept) => {
    setProjects((current) => current.map((project) => (project.id === id ? touch({ ...project, design }) : project)));
  }, []);

  const savePricing = useCallback((id: string, pricing: ProjectPricing) => {
    setProjects((current) => current.map((project) => (project.id === id ? touch({ ...project, pricing }) : project)));
  }, []);

  /**
   * Undo/redo for AI edits, persisted with the project.
   *
   * Only the FIELDS an edit actually touched are stored, not whole concept snapshots — a designer
   * edit changes a palette, a style or one price, so a diff is a fraction of the size of the
   * document and the stack survives a reload without bloating storage. The stack is capped, and
   * the oldest step is dropped first.
   */
  const historyRef = useRef<Map<string, { past: (WebsiteConcept | null)[]; future: (WebsiteConcept | null)[] }>>(new Map());
  // Refs don't re-render, but the Undo/Redo buttons must enable and disable as the stack moves.
  const [, bumpHistory] = useState(0);

  const stackFor = (id: string) => {
    let stack = historyRef.current.get(id);
    if (!stack) {
      stack = { past: [], future: [] };
      historyRef.current.set(id, stack);
    }
    return stack;
  };

  const pushHistory = useCallback((id: string, previous: WebsiteConcept | null, next: WebsiteConcept | null) => {
    const stack = stackFor(id);
    // A new edit invalidates anything that was undone — the classic branch-and-drop.
    stack.past.push(previous);
    stack.future = [];
    if (stack.past.length > 30) stack.past.shift();
    bumpHistory((value) => value + 1);
    setProjects((current) =>
      current.map((project) =>
        project.id === id
          ? { ...project, editHistory: [...project.editHistory, conceptDiff(previous, next)].slice(-20), redoHistory: [] }
          : project,
      ),
    );
  }, []);

  /**
   * The stack is moved BEFORE setProjects, never inside its updater. React intentionally invokes
   * updater functions twice in development, so a pop() in there ran twice and undid two steps on
   * the first click — updaters must stay pure.
   */
  const undo = useCallback((id: string) => {
    const stack = stackFor(id);
    // In-session stack first (exact snapshots); otherwise replay the persisted diff, which is
    // what makes undo survive a reload.
    if (stack.past.length) {
      const previous = stack.past.pop() ?? null;
      let reverted = false;
      setProjects((current) =>
        current.map((project) => {
          if (project.id !== id) return project;
          if (!reverted) {
            stack.future.push(project.design);
            reverted = true;
          }
          return touch({ ...project, design: previous, editHistory: project.editHistory.slice(0, -1), redoHistory: [...project.redoHistory, conceptDiff(project.design, previous)] });
        }),
      );
      bumpHistory((value) => value + 1);
      return;
    }
    setProjects((current) =>
      current.map((project) => {
        if (project.id !== id || !project.editHistory.length) return project;
        const diff = project.editHistory[project.editHistory.length - 1];
        return touch({
          ...project,
          design: applyConceptDiff(project.design, diff),
          editHistory: project.editHistory.slice(0, -1),
          redoHistory: [...project.redoHistory, conceptDiff(project.design, applyConceptDiff(project.design, diff))],
        });
      }),
    );
    bumpHistory((value) => value + 1);
  }, []);

  const redo = useCallback((id: string) => {
    const stack = stackFor(id);
    if (stack.future.length) {
      const next = stack.future.pop() ?? null;
      let restored = false;
      setProjects((current) =>
        current.map((project) => {
          if (project.id !== id) return project;
          if (!restored) {
            stack.past.push(project.design);
            restored = true;
          }
          return touch({ ...project, design: next, redoHistory: project.redoHistory.slice(0, -1), editHistory: [...project.editHistory, conceptDiff(project.design, next)] });
        }),
      );
      bumpHistory((value) => value + 1);
      return;
    }
    setProjects((current) =>
      current.map((project) => {
        if (project.id !== id || !project.redoHistory.length) return project;
        const diff = project.redoHistory[project.redoHistory.length - 1];
        const restoredDesign = applyConceptDiff(project.design, diff);
        return touch({
          ...project,
          design: restoredDesign,
          redoHistory: project.redoHistory.slice(0, -1),
          editHistory: [...project.editHistory, conceptDiff(project.design, restoredDesign)],
        });
      }),
    );
    bumpHistory((value) => value + 1);
  }, []);

  const canUndo = useCallback(
    (id: string) =>
      Boolean(historyRef.current.get(id)?.past.length) ||
      Boolean(projects.find((project) => project.id === id)?.editHistory.length),
    [projects],
  );
  const canRedo = useCallback(
    (id: string) =>
      Boolean(historyRef.current.get(id)?.future.length) ||
      Boolean(projects.find((project) => project.id === id)?.redoHistory.length),
    [projects],
  );

  const appendDesignerEntry = useCallback((id: string, entry: DesignerEntry) => {
    setProjects((current) =>
      current.map((project) =>
        // Capped so a long-lived project cannot grow its stored history without bound; the most
        // recent decisions are the ones later requests need.
        project.id === id ? touch({ ...project, designerLog: [...project.designerLog, entry].slice(-40) }) : project,
      ),
    );
  }, []);

  const publish = useCallback((id: string) => {
    setProjects((current) =>
      current.map((project) => (project.id === id ? touch({ ...project, publishedAt: Date.now() }) : project)),
    );
  }, []);

  const unpublish = useCallback((id: string) => {
    setProjects((current) =>
      current.map((project) => (project.id === id ? touch({ ...project, publishedAt: null }) : project)),
    );
  }, []);

  const briefFor = (project: Project): ProjectBrief => ({
    name: project.name,
    businessType: project.businessType,
    city: project.city,
    description: project.businessDescription,
    styleIds: project.preferredStyleIds,
    colorIds: project.preferredColorIds,
    goals: project.goals,
    sections: project.sections,
    wishes: project.wishes,
  });

  const run = useCallback(async (project: Project, scope: GenerationScope[]) => {
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;
    setGeneration({ projectId: project.id, stage: generationStages[0].id, scope });

    try {
      const result = await runProjectGeneration(
        briefFor(project),
        (stage) => setGeneration((current) => (current ? { ...current, stage } : current)),
        controller.signal,
      );
      // Written in one update so a project never exists in a half-generated state on disk.
      setProjects((current) =>
        current.map((item) =>
          item.id === project.id
            ? touch({
                ...item,
                analysis: scope.includes("analysis") ? result.analysis ?? item.analysis : item.analysis,
                design: scope.includes("design") ? result.design ?? item.design : item.design,
                pricing: scope.includes("pricing") ? result.pricing ?? item.pricing : item.pricing,
                generatedAt: item.generatedAt ?? Date.now(),
              })
            : item,
        ),
      );
    } finally {
      if (abortRef.current === controller) abortRef.current = null;
      setGeneration(null);
    }
  }, []);

  const generateAll = useCallback(
    (project: Project) => run(project, ["analysis", "design", "pricing"]),
    [run],
  );

  const regenerate = useCallback(
    (project: Project, scope: GenerationScope) => run(project, [scope]),
    [run],
  );

  const value = useMemo<ProjectsContextValue>(
    () => ({
      projects,
      isLoaded,
      saveState,
      retrySave,
      storage: signedIn ? "account" : "device",
      loadError,
      migrationError,
      create,
      rename,
      duplicate,
      remove,
      getProject,
      saveAnalysis,
      saveDesign,
      savePricing,
      appendDesignerEntry,
      pushHistory,
      undo,
      redo,
      canUndo,
      canRedo,
      publish,
      unpublish,
      generation,
      generateAll,
      regenerate,
    }),
    [projects, isLoaded, saveState, retrySave, signedIn, loadError, migrationError, create, rename, duplicate, remove, getProject, saveAnalysis, saveDesign, savePricing, appendDesignerEntry, pushHistory, undo, redo, canUndo, canRedo, publish, unpublish, generation, generateAll, regenerate],
  );

  return <ProjectsContext.Provider value={value}>{children}</ProjectsContext.Provider>;
}

export function useProjects() {
  const value = useContext(ProjectsContext);
  if (!value) throw new Error("useProjects must be used within a ProjectsProvider");
  return value;
}
