"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import type { AnalysisResult, EstimateForm, EstimateResult } from "@/components/site-experience";
import type { WebsiteConcept } from "@/lib/website-concept";
import { projectRepository } from "./project-repository";

/**
 * The central object of the Workspace. A Project is one business worked on end-to-end: the AI
 * Consultant's analysis, the Design Studio's concept (which already carries its own selected
 * colors/style — see WebsiteConcept), and the Pricing calculator's form + result all live on the
 * SAME project instead of each tool inventing its own disconnected "saved item". There is no
 * separate `workflow` field: the workflow map is `analysis.flow`, already generated by the AI
 * Consultant — storing it twice would just be two copies that can drift apart.
 */
export type ProjectPricing = {
  form: EstimateForm;
  result: EstimateResult;
};

export type Project = {
  id: string;
  name: string;
  /** Free text — may come from the Design Studio wizard's ConceptBusinessType or from the
   * Hero's detected business label, so it's a plain string rather than either union type. */
  businessType: string;
  /** The original free-text description that seeded this project (from BusinessProvider). */
  businessDescription: string;
  favorite: boolean;
  createdAt: number;
  updatedAt: number;
  analysis: AnalysisResult | null;
  design: WebsiteConcept | null;
  pricing: ProjectPricing | null;
};

export type CreateProjectInput = {
  name: string;
  businessType: string;
  businessDescription: string;
};

/**
 * Deliberately NOT a stored field on Project — completion state is derived from what's actually
 * there, so it can never drift out of sync with the real content the way a cached `status`
 * string could.
 */
export type ProjectProgress = {
  hasAnalysis: boolean;
  hasDesign: boolean;
  hasWorkflow: boolean;
  hasPricing: boolean;
  completedCount: number;
  totalCount: number;
};

export function getProjectProgress(project: Project): ProjectProgress {
  const hasAnalysis = Boolean(project.analysis);
  const hasDesign = Boolean(project.design);
  const hasWorkflow = Boolean(project.analysis?.flow.length);
  const hasPricing = Boolean(project.pricing);
  const flags = [hasAnalysis, hasDesign, hasPricing];
  return {
    hasAnalysis,
    hasDesign,
    hasWorkflow,
    hasPricing,
    completedCount: flags.filter(Boolean).length,
    totalCount: flags.length,
  };
}

type ProjectsContextValue = {
  projects: Project[];
  /** Most recently touched first — what "Recent" filters/sorts by, no separate storage needed. */
  recent: Project[];
  favorites: Project[];
  /** False until the initial localStorage read completes — lets a consumer distinguish "still
   * loading" from "genuinely no projects" if that distinction ever matters. */
  isLoaded: boolean;
  create: (input: CreateProjectInput) => Project;
  rename: (id: string, name: string) => void;
  duplicate: (id: string) => Project | null;
  remove: (id: string) => void;
  toggleFavorite: (id: string) => void;
  getProject: (id: string) => Project | null;
  saveAnalysis: (id: string, analysis: AnalysisResult) => void;
  saveDesign: (id: string, design: WebsiteConcept) => void;
  savePricing: (id: string, pricing: ProjectPricing) => void;
};

const ProjectsContext = createContext<ProjectsContextValue | null>(null);

function createId() {
  return typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `project-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
}

function touch<T extends { updatedAt: number }>(project: T): T {
  return { ...project, updatedAt: Date.now() };
}

/**
 * Persists through `projectRepository` (localStorage today, swappable for a real backend later
 * without touching any page — every consumer goes through `useProjects()`).
 *
 * Hydration safety: initial state is always `[]`, identical on server and first client render.
 * The real data (if any) loads one tick later in an effect that never runs during SSR, so the
 * only thing that changes post-hydration is a normal state update — never a server/client
 * mismatch.
 */
export function ProjectsProvider({ children }: { children: ReactNode }) {
  const [projects, setProjects] = useState<Project[]>([]);
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    setProjects(projectRepository.load());
    setIsLoaded(true);
  }, []);

  // Skip the very first run (before the load above has happened) so it can't stomp real stored
  // data with the initial empty array.
  useEffect(() => {
    if (!isLoaded) return;
    projectRepository.save(projects);
  }, [projects, isLoaded]);

  const create = useCallback((input: CreateProjectInput) => {
    const now = Date.now();
    const project: Project = {
      id: createId(),
      name: input.name,
      businessType: input.businessType,
      businessDescription: input.businessDescription,
      favorite: false,
      createdAt: now,
      updatedAt: now,
      analysis: null,
      design: null,
      pricing: null,
    };
    setProjects((current) => [project, ...current]);
    return project;
  }, []);

  const rename = useCallback((id: string, name: string) => {
    const trimmed = name.trim();
    if (!trimmed) return;
    setProjects((current) => current.map((project) => (project.id === id ? touch({ ...project, name: trimmed }) : project)));
  }, []);

  const duplicate = useCallback(
    (id: string) => {
      const source = projects.find((project) => project.id === id);
      if (!source) return null;
      const now = Date.now();
      const copy: Project = { ...source, id: createId(), name: `${source.name} (копия)`, favorite: false, createdAt: now, updatedAt: now };
      setProjects((current) => [copy, ...current]);
      return copy;
    },
    [projects],
  );

  const remove = useCallback((id: string) => {
    setProjects((current) => current.filter((project) => project.id !== id));
  }, []);

  const toggleFavorite = useCallback((id: string) => {
    setProjects((current) =>
      current.map((project) => (project.id === id ? touch({ ...project, favorite: !project.favorite }) : project)),
    );
  }, []);

  const getProject = useCallback((id: string) => projects.find((project) => project.id === id) ?? null, [projects]);

  const saveAnalysis = useCallback((id: string, analysis: AnalysisResult) => {
    setProjects((current) => current.map((project) => (project.id === id ? touch({ ...project, analysis }) : project)));
  }, []);

  const saveDesign = useCallback((id: string, design: WebsiteConcept) => {
    setProjects((current) => current.map((project) => (project.id === id ? touch({ ...project, design }) : project)));
  }, []);

  const savePricing = useCallback((id: string, pricing: ProjectPricing) => {
    setProjects((current) => current.map((project) => (project.id === id ? touch({ ...project, pricing }) : project)));
  }, []);

  const value = useMemo<ProjectsContextValue>(() => {
    const byRecency = [...projects].sort((a, b) => b.updatedAt - a.updatedAt);
    return {
      projects,
      recent: byRecency.slice(0, 5),
      favorites: projects.filter((project) => project.favorite),
      isLoaded,
      create,
      rename,
      duplicate,
      remove,
      toggleFavorite,
      getProject,
      saveAnalysis,
      saveDesign,
      savePricing,
    };
  }, [projects, isLoaded, create, rename, duplicate, remove, toggleFavorite, getProject, saveAnalysis, saveDesign, savePricing]);

  return <ProjectsContext.Provider value={value}>{children}</ProjectsContext.Provider>;
}

export function useProjects() {
  const value = useContext(ProjectsContext);
  if (!value) throw new Error("useProjects must be used within a ProjectsProvider");
  return value;
}
