"use client";

import Link from "next/link";
import { ArrowRight, Workflow as WorkflowIcon } from "lucide-react";
import { useCurrentProject } from "@/components/workspace/use-current-project";
import { projectHref } from "@/components/workspace/project-nav";
import { WorkspaceEmptyState } from "@/components/workspace/empty-state";

/** Read-only — the workflow map IS `project.analysis.flow`, generated by the AI Consultant.
 * There's no separate authoring step here, so no separate data to store or drift out of sync. */
export default function ProjectWorkflowPage() {
  const { project, projectId } = useCurrentProject();

  if (!project || !projectId) return null;

  const flow = project.analysis?.flow ?? [];

  if (!flow.length) {
    return (
      <WorkspaceEmptyState
        icon={WorkflowIcon}
        title="Карта процесса ещё не построена"
        description="Процесс строится автоматически по итогам AI-анализа — запустите его, чтобы увидеть шаги."
        action={
          <Link href={projectHref(projectId, "ai-consultant")} className="workspace-topbar-action">
            Запустить AI-анализ <ArrowRight className="ml-1.5 h-4 w-4" />
          </Link>
        }
      />
    );
  }

  return (
    <div className="workspace-workflow-list">
      {flow.map((step, index) => (
        <div key={`${step}-${index}`} className="workspace-workflow-step">
          <span className="workspace-workflow-step-index">{index + 1}</span>
          <span>{step}</span>
        </div>
      ))}
    </div>
  );
}
